### ISSUE TITLE
Create obstacle object protoptype

### ISSUE THREAD

**Issue by nicolasbock** [video-game-coding-club/geometry-smash#134]
It would help for #133 if the extent properties came from an obstacle prototype. Then the naming would automatically be consistent.

https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object_prototypes

**Comment by aparrett** [comment]
I would like to take a look at this one.

**Comment by aparrett** [comment]
What algorithm are you planning to use to detect collisions? This would appear to have a great impact on which properties are necessary to keep track of.

**Comment by nicolasbock** [comment]
Now looking into this a bit more I came across

https://developer.mozilla.org/en-US/docs/Games/Techniques/2D_collision_detection

And there are a few options listed there. I was hoping we could start out really simple like in the axis-aligned bounding box case or possibly a combination of the circle collision (since the hero is basically a circle) and the bounding box, but some obstacles are pretty complex already and I don't know whether a simple bounding box would be enough. As an alternative, I am going to take a closer look at the separating axis theorem to see just how complicated that is to implement.

In the meantime though we could start with a bounding box and accept the fact that collisions are not detected overly precisely. But at least we could start playing the game then :wink:

**Comment by aparrett** [comment]
That is the same resource I stumbled upon earlier.  Implementing SAT sounds awesome but pretty difficult as well.

**Comment by aparrett** [comment]
[This](https://github.com/jriecken/sat-js) library for SAT looks pretty awesome at first glance.

**Comment by nicolasbock** [comment]
@aparrett Have a look at #142 and #144.

Within this game the collision detection algorithm could be simplified from the general case that SAT or the Mozilla reference are trying to address since the hero's movement is quite restricted. While I am not convinced that using only one corner of a bounding box is enough, I think it's a nice start.

What do you think? You could start with prototyping that one corner or generalize right away to an axis-aligned bounding box.

**Comment by aparrett** [comment]
I am going to try to take a look at this sometime today or over the weekend 😃

**Comment by nicolasbock** [comment]
One point I forgot to mention regarding external libraries: Currently we are hosting the game on GitHub's infrastructure. If we want to use an external library we would have to copy the library code into this repository as far as I understand. At this point I would prefer if we would avoid having to do that.

And thanks again for looking into this issue!

**Comment by nicolasbock** [comment]
Closing for now.
